### ISSUE TITLE
Error: There was an error when attempting to execute the process 'gradlew'. This may indicate the process failed to start. Error: spawn gradlew ENOENT

### ISSUE THREAD

**Issue by karim-haned** [moatazeldebsy/appium-github-actions-integration#11]
Hi Nabil ! 
Thanks for sharing this amazing template. I have used the same one for my gradle mobile testing. However , during github action run I encounter this error :Error: There was an error when attempting to execute the process 'gradlew'. This may indicate the process failed to start. Error: spawn gradlew ENOENT
![image](https://user-images.githubusercontent.com/68304005/155196762-7b81fc6d-fa13-434d-be40-1b680f6bfbf8.png)
Any help will be much appreciated 
Karim

**Comment by moatazeldebsy** [comment]
Hi @karim-haned thank you, can you share with me which Gradle version you are using?

**Comment by karim-haned** [comment]
Hi @moatazeldebsy , I use this version for now and it works only locally when I run my test using gradlew test --info command 
![image](https://user-images.githubusercontent.com/68304005/155541173-b6381fe7-baa7-4862-a8de-100c45e25057.png)
